on: [push, pull_request]
name: CI

jobs:
  build:
    strategy:
      matrix:
        #os: [ubuntu-latest, macos-latest]
        os: [ubuntu-latest]
        name: [
          production,
          production-clang,
          debug,
          debug-clang
        ]

        exclude:
          - name: production-clang
            os: macos-latest

          - name: debug-clang
            os: macos-latest

        include:
          - name: production
            config:

          - name: production-clang
            config:
            env: CC=clang CXX=clang++

          - name: debug
            config: -Dbuildtype=debug

          - name: debug-clang
            config: -Dbuildtype=debug
            env: CC=clang CXX=clang++

    name: ${{ matrix.os }}:${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Install Packages (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libgmp-dev \
            libgtest-dev \
            ninja-build
          python3 -m pip install meson
          echo "$(python3 -m site --user-base)/bin" >> $GITHUB_PATH
          cd /usr/src/googletest
          sudo cmake .
          sudo cmake --build . --target install
          cd -

      - name: Install Packages (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install gmp pkgconfig ninja googletest
          python3 -m pip install meson
          echo "$(python3 -m site --user-base)/bin" >> $GITHUB_PATH

      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure
        run: ${{ matrix.env }} meson setup build ${{ matrix.config }}

      - name: Build
        run: meson compile
        working-directory: build

      - name: Test
        run: meson test --print-errorlogs
        working-directory: build
