on: [push, pull_request]
name: CI

jobs:
  build:
    strategy:
      matrix:
        #os: [ubuntu-latest, macos-latest]
        os: [ubuntu-latest]
        name: [
          production,
          production-clang,
          debug,
          debug-clang
        ]

        exclude:
          - name: production-clang
            os: macos-latest

          - name: debug-clang
            os: macos-latest

        include:
          - name: production
            config:

          - name: production-clang
            config:
            env: CC=clang CXX=clang++

          - name: debug
            config: debug

          - name: debug-clang
            config: debug
            env: CC=clang CXX=clang++

    name: ${{ matrix.os }}:${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Install Packages (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libgmp-dev \
            libgtest-dev
          cd /usr/src/googletest
          sudo cmake .
          sudo cmake --build . --target install
          cd -

      - name: Install Packages (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install gmp
          brew install googletest

      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure
        run: |
          ${{ matrix.env }} ./configure.sh ${{ matrix.config }}

      - name: Build
        run: make -j2
        working-directory: build

      - name: Run CTest
        run: ctest -j2 --output-on-failure
        working-directory: build
